version: "3.9"

x-airflow-common: &airflow-common
  image: apache/airflow:2.10.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW_WEBSERVER_SECRET_KEY: "changeme"
    PYTHONPATH: "/opt/project/src"
    MLFLOW_TRACKING_URI: "http://mlflow:5000"
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ..:/opt/project
  user: "50000"
  depends_on:
    - airflow-postgres
    - mlflow

services:

  airflow-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  mlflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    depends_on:
      - mlflow-db
    volumes:
      - ./mlflow-artifacts:/mlflow-artifacts
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://mlflow:mlflow@mlflow-db:5432/mlflow
      --default-artifact-root /mlflow-artifacts
      --host 0.0.0.0
      --port 5000

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname Raj
      --lastname Admin
      --role Admin
      --email admin@creditcardfrauddetection.com
      "

volumes:
  airflow_db_data:
  mlflow_db_data:
